server:
  port: 9004
spring:
  application:
    #应用的名称，可选
    name: mimi
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ENC(W3Seehykt7vc6A2yocLfSvQnfaS4QNnkISaoXIYYTXw=)
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: dev
#    password: root123
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true

jasypt:
  encryptor:
    #加密盐
    password: +oE67TSCE/j7==
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

ali:
  accessKeyId: ENC(ADD8NveA0RYJi5yj8lJBUVKvgykBgR8bw8s1OSI9jU3TXrcXbCFvwg==)
  accessSecret: ENC(mVhlQRB1CH4u94p5GMCwvG1zlzefFPfShqnvV9EfS9mIcK2CmKcVmA==)

