server:
  port: 9004
spring:
  application:
    #应用的名称，可选
    name: mimi
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.98.203.215:3306/pig-school-config?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 28dyKp8JX23NEMmA

#      url: jdbc:mysql://localhost:3306/pig-school-config?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: root
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: 127.0.0.1
    port: 6379
#    password: root123
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true

kd:
  public:
    fileroot: /root/public
  pay:
    fileroot: /root/pay
  door:
    appsecret: f5a8a6c470c1404937fd2ffb00b5a6bea653aff06b313d3c76f50df492d83fbc
  wx:
    appId: 1
    appSecret: 1
    code2Session:
      url: https://api.weixin.qq.com/sns/oauth2/access_token?appid={0}&secret={1}&code={2}&grant_type=authorization_code
    notify:
      url: https://127.0.0.1/guest/pay/notice